### ISSUE TITLE
Elixir Phoenix support

### ISSUE THREAD

**Issue by palkan** [palkan/wsdirector#12]
## Is your feature request related to a problem? Please describe.

It would be nice to have [Phoenix Channels](https://hexdocs.pm/phoenix/channels.html) support out-of-the-box.

## Describe the solution you'd like

Here is how we can communicate with Phoenix today:

```yml
---
- send:
    data:
      topic: "post:1"
      event: phx_join
      payload: {}
      ref: '1'
- receive:
    data:
      topic: "post:1"
      ref: '1'
      payload:
        status: ok
        response: {}
      event: phx_reply
- send:
    data:
      topic:"post:1"
      event: "submit_comment"
      payload:
        message:
          text: "That's nice"
      ref: '2'
```

With `phoenix` protocol, that could look like:

```yml
- client:
    protocol: "phoenix"
    actions:
       - join:
           topic: "posts:1" 
       - send:
           topic:  "posts:1"
           event: "submit_comment"
           payload:
             message:
               text: "That's even nicer"
```

## Open questions

- What about heartbeats? (Or we can ignore them)
- Can we automatically add `refs`?
