### ISSUE TITLE
Add loops supports

### ISSUE THREAD

**Issue by palkan** [palkan/wsdirector#7]
## Problem

Sometimes it's useful to perform a similar set of actions multiple times (send - receive - sleep - send - receive - sleep ...).
Currently, it's only possible via copy-paste.

## Describe the solution you'd like

Here is a proposed syntax:

```yml
- receive: "Welcome" # expect to receive message
- loop: 
    multiplier: 3 # should support :scale
    actions:
      - send:
          data: "send message" # send message, all messages in data will be parse to json
      - receive:
          data: "receive message" # expect to receive json message
```
